### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jonsterling** [freebroccolo/vscode-redprl#16]
Whenever you get a chance, let's release a new version of this extension, since I'm ready to release the version of RedPRL that these updates pertain to.

Thanks!!

**Comment by freebroccolo** [comment]
Cool. I'll try to make a release tomorrow since I need to get a few things setup again first.

**Comment by freebroccolo** [comment]
I just pushed a new version. I didn't get a chance to test it with RedPRL in the dev environment I'm currently using but I didn't make any other changes so it should be okay. Let me know if there are problems.

**Comment by jonsterling** [comment]
thanks!
