### ISSUE TITLE
Refresh diagnostics while editing

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/vscode-redprl#2]
It would be very easy to implement this on the editor side but we would want to be able to support it without having to save the document or save to an intermediate file first.

Probably the most straightforward thing to do would be to modify the `redprl` binary to read the piped contents of a `.prl` file from `stdin`. Example usage could look something like `cat Test.prl | redprl --from-stdin Test.prl`. The argument to `--from-stdin` would be used purely for the reported diagnostic locations.

@jonsterling

**Comment by jonsterling** [comment]
This sounds like a very good idea, and it should be easy to implement.
