### ISSUE TITLE
Codelens to display remaining goals

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/vscode-redprl#5]
It might be interesting to show the number of remaining goals above the theorems, etc. It's a little messy to calculate that currently though because we would have to determine which item the goals belong to by range inclusion or something. Doable but a lot less efficient than it could be.

@jonsterling could the `Warning` output be changed to include the name of the enclosing item? That would make this trivial to implement.

**Comment by freebroccolo** [comment]
Maybe the name is not a great idea actually if there is the possibility of shadowing. But the range of the enclosing item should be enough if it is exactly the same as what gets shown for `Output` because then we can just use a table or something.

**Comment by jonsterling** [comment]
@freebroccolo I think we can certainly do this...

**Comment by freebroccolo** [comment]
So I have this implemented in a naive way now.

![codelens](https://cloud.githubusercontent.com/assets/151197/19877646/abc7a86a-9fa6-11e6-97c9-1885653c2dc3.png)

I think I will hold off on merging it until #2 is supported though because otherwise we need to keep track of the positioning for the code lens according to buffer edits that have not been saved to disk yet. If we get support for refreshing during editing we can just have `redprl` recompute the new locations for us.

**Comment by freebroccolo** [comment]
Also I think the implementation is fine for now and doesn't require any changes to the output. It's not particularly efficient because it loops through the symbols to find the enclosing range but the developments are small enough that it doesn't really matter.
