### ISSUE TITLE
Integrate or recommend prettify symbols mode

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/vscode-redprl#8]
There is a vscode extension called [prettify symbols mode](https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode) which is similar to the emacs mode of the same name.

I've tried it briefly and it seems to work pretty well. I've included a screenshot using this extension with the following settings:

```json
{
  "language": "redprl",
  "substitutions": [
    { "ugly": "->", "pretty": "⟶" },
    { "ugly": "=>", "pretty": "⇒" },
    { "ugly": "\\.", "pretty": "∎", "pre": "\\]\\s*", "post": "\\s*(?:$|\\b(?:Def|Print|Tac|Thm)\\b)" },
    { "ugly": "\\bDef\\b", "pretty": "𝔇𝔢𝔣" },
    { "ugly": "\\bPrint\\b", "pretty": "𝔓𝔯𝔦𝔫𝔱" },
    { "ugly": "\\bTac\\b", "pretty": "𝔗𝔞𝔠" },
    { "ugly": "\\bThm\\b", "pretty": "𝔗𝔥𝔪" },
    { "ugly": "\\bby\\b", "pretty": "∵" },
    { "ugly": "\\blam\\b", "pretty": "λ" }
  ]
}
```

We could install this as a dependency but it would probably be better for now to just mention it somewhere and suggest a default configuration if people want to try it.

![pretty](https://cloud.githubusercontent.com/assets/151197/20039803/ac520ce8-a407-11e6-88a3-0e1046da7fd8.png)

**Comment by jonsterling** [comment]
Just tried this out, it works pretty well!

**Comment by freebroccolo** [comment]
Yeah, I haven't used it in awhile but it seemed pretty flexible last time I tried it. I think we could add it as a recommended extension or something so it would show up when the user installs the redprl plugin. Might want to have a little tutorial on how to use it or something in that case.

**Comment by freebroccolo** [comment]
My impression is that this package is not being maintained anymore so I no longer think it's a good idea to integrate it into the RedPRL extension.
