### ISSUE TITLE
Document how to use input assist

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/vscode-redprl#9]
I've added a dependency to the [input assist](https://github.com/freebroccolo/vscode-input-assist) plugin which (at the moment) is basically just a port of the agda input method. It can be used with this extension by adding "redprl" to the list of enabled languages:

```
"input-assist.languages": ["redprl"]
```

This should be documented somewhere along with an explanation of how the agda style completion is supposed to work.

**Comment by freebroccolo** [comment]
Originally I thought this might be useful to have at least for unicode in comments but now I'm not sure. What do you think @jonsterling? If it isn't really being used it might be better to drop the dependency.

**Comment by jonsterling** [comment]
I think it probably is not needed as a dep for now... We don't have many redprl documents in the world yet, so time will tell what we need.

**Comment by freebroccolo** [comment]
Alright, I've removed it. Can always add it back later if needed.
